name: Deploy to Airflow Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy to EC2'
    runs-on: ubuntu-latest
    # permissions: ...
    steps:
      - name: Checkout github repo
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: actions/configure-aws-credentials@v1
      - name: Deploy to EC2
        run: |
          echo "Deploying branch ${{ env.GITHUB_REF }}"
