name: Deploy to Airflow Server

on:
  push:
    branches: [dev]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build Machine
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Setup JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

  deploy:
    name: Deploy to EC2'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout github repo
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy to EC2
        run: |
          echo AWS region is: ${{ secrets.AWS_REGION }}
          echo "Deploying ${{ github.ref }} branch in repository ${{ github.repository }} on ${{ github.event_name }}"
          aws deploy create-deployment --application-name ${{ secrets.CODE_DEPLOY_APP_NAME }}  --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name ${{ secrets.CODE_DEPLOY_GROUP_NAME }} --description "Spotify ETL GitHub deployment" --github-location repository=${{ github.repository }},commitId=${{ github.sha }} --ignore-application-stop-failures true
