name: Deploy to Airflow Server

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build Machine
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: List Buckets
        run: |
          aws s3 ls
      - name: Setup JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 17

  deploy:
    name: Deploy to EC2'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout github repo
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: List Buckets
        run: |
          aws s3 ls
      - name: Deploy to EC2
        run: |
          echo AWS region is: ${{ secrets.AWS_REGION }}
          echo "Deploying branch ${{ env.GITHUB_REF }}"
          aws deploy create-deployment
